FROM pytorch:2.2.1-cuda11.8-cudnn8-runtime

RUN apt update -y
RUN apt install -y libgl1-mesa-glx \
libglib2.0-0

RUN pip install imageio \
insightface==0.2.1 \
onnxruntime \
moviepy \
onnxruntime-gpu \
mlflow \
minio \
boto3
