FROM pytorch/pytorch:2.2.1-cuda11.8-cudnn8-runtime

ARG start_path /workspace
ARG base_path $start_path/serving/SwimSwap
COPY . $start_path
RUN mkdir -p $base_path/insightface_func/models \
$base_path/parsing_model/checkpoint \
$base_path/arcface_model

RUN apt update -y
RUN apt install -y libgl1-mesa-glx \
libglib2.0-0

ADD http://223.130.133.236:9000/voice2face-public/model_resource/swimswap/79999_iter.pth $base_path/parsing_model/checkpoint

ADD http://223.130.133.236:9000/voice2face-public/model_resource/swimswap/antelope.zip $base_path/xinsightface_func/models


RUN pip install imageio \
insightface==0.2.1 \
onnxruntime \
moviepy \
onnxruntime-gpu \
mlflow \
minio \
boto3

CMD [ "cd","$base_path" ]
CMD [ "python", "inference.py" ]